### ISSUE TITLE
Cleanup graphnode and monitor DB

### ISSUE THREAD

**Issue by jay-kim-kor** [Bisonai/orakl#1236]
# TODO
- [x] Investigate size of each services(Data Feed, VRF, RR)
  - [DB size chart](https://docs.google.com/spreadsheets/d/1goBweHvWWdB8qhtKsbff4qMah-vBc5JsQjRV0dnsRiY/edit?usp=sharing)
- [x] List-up removable data(it isn't need keep old data) in Data Feed
  - #1141 (WIP)
- [ ] `#a` Investigate removable data in VRF or RR(#1080)
- [ ] Write migration script to delete removable data that related to Data Feed
- [ ] (Depended `#a`) Write migration script to delete old data that related to VRF, RR

**Comment by jay-kim-kor** [comment]
This issue is have two sub-issues. But, graph-node closed. So, I'll close it. Because it's duplicated #1080.
