### ISSUE TITLE
Use single GKE cluster

### ISSUE THREAD

**Issue by jay-kim-kor** [Bisonai/orakl#1239]
# Purpose
- Saving GKE cluster management cost, it charged $74/mon of every standard cluster.
- Easy access, maintain, deploy

# Namespace structure
- Important node(must keep running)
  - `cypress`: Run Orakl in Cypress
  - `orakl-helper`: OVPN, JSON-RPC node, proxy for fetcher, orakl-backend-fe
  - `monitoring`: graphnode VM, grafana, bisontry
- Common node
  - `baobab`: Run Orakl in Baobab
  - `argocd`
  - `playground`: Run VMs for testing

# TODO
- [ ] Investigate limitation of connections.
- [ ] Estimate how much we can save?
- [ ] Waiting decision what we migrate Orakl to IDC or not.
- [ ] Create Autopilot cluster to `vpc-host-orakl-prod` project.
- [ ] Add `argocd`, `playground`.
- [ ] Add helm-chart generator.
  - `values.yaml` must include part to select node
- [ ] Migrate `orakl-helper`.
- [ ] Autopilot Operating Test: Confirm if the crash problem reoccurs.
- [ ] Migrate Baobab.
- [ ] Migrate `monitoring`.
- [ ] Migrate Cypress.
- [ ] Cleanup and delete old projects are `orakl-baobab-prod` and `orakl-cypress-prod`.
- [ ] Rename `vpc-host-orakl-prod` project to `orakl`.

**Comment by martinkersner** [comment]
@jay-kim-kor Can we close this issue?

**Comment by jay-kim-kor** [comment]
> @jay-kim-kor Can we close this issue?

Yes, I'll close it.
